### PR TITLE
Modify cases

### PR DESCRIPTION
**Pull request by sysdl132**
I add some cases for m5.They are:
* [3DPrintfiles](https://github.com/m4k3r-org/M5Stack-3DPrintFiles) - Links to files for 3D printing custom case parts for the M5Stack.

* [Covid-19_monitor](https://github.com/electricidea/M5Stack-Covid19-Monitor) - Code to graphically display the current data of the Covid-19 pandemic

* [homepoint](https://github.com/sieren/Homepoint) - Espressif ESP32 Based Smarthome screen for MQTT.Manage your home now!

* [tinybasicplus-for-m5](https://github.com/0x1abin/M5Stack_TinyBasicPlus) - A remix from tinybasicplus

* [Chat_APP_M5Stack](https://github.com/sysdl132/Chat_APP_M5Stack) - Prototype chat application using MQTT with M5Stack.A remix from tanopanta/Chat_APP_M5Stack

* [Tensorflow_microspeech](https://github.com/boochow/TFLite_Micro_MicroSpeech_M5Stack) - M5Stack (ESP32) port of TensorFlow Lite for Microcontrollers demo "Micro Speech"

* [LovyanLauncher](https://github.com/lovyan03/M5Stack_LovyanLauncher) - M5Stack Tools & Application Launcher

(I modified en and zh_cn at the same time.But the examples was **not been** tested on my M5Stack!)

- [ ] Is it good?(<-)

[preview here](https://deploy-preview-166--m5-docs.netlify.app/)

### CODE REVIEW

**Comment by sysdl132** [comment]
(if the check was success,I will mark it as ready for review)

**Comment by sysdl132** [comment]
https://github.com/m5stack/m5-docs/issues/167

**Comment by sysdl132** [comment]
?????
is there any person

**Comment by sysdl132** [comment]
?????
# IS THERE ANY PERSON ONLINE?

**Comment by sysdl132** [comment]
@EeeeBin Reply?(pull request linked to #167 )

**Comment by EeeeBin** [comment]
Hi, sysdl132
Thanks for you PR and sorry for the long lack of response
Tomorrow we will merge this PR

**Comment by sysdl132** [comment]
thanks for reply  👍

**Pull request merged**
